### ISSUE TITLE
The blocked stories from the "For You" section reappear in future results

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [LaserlikeInc/firefox-addon#50]
**[Affected versions]:**
- Firefox 61.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Laserlike (0.9.26) version installed on a new Firefox profile.
- Have enough history to have the "For You" section populated.
- The Laserlike sidebar is opened.

**[Steps to reproduce]:**
1. Open browser with the profile from prerequisites.
2. From the "For You" section click on the "..." button of a story.
3. Click the "Block [website_name]" option.
4. Close and reopen the sidebar.
5. Observe the "For You" section.

**[Expected result]:**
- The blocked story is no longer displayed.

**[Actual result]:**
- The blocked story reapers.

**[Notes]**
- The issue is also reproducible for the blocked stories from the "For You" section from the Laserlike homepage.
- Here is a screen recording of the issue:
![blocked website](https://user-images.githubusercontent.com/19226534/43530741-facf2e6c-95b6-11e8-8a60-4190a1162ebc.gif)

**Comment by sg-laserlike** [comment]
This is fixed in the new push, please re-test.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using latest Laserlike (0.9.35) version and the issue is still reproducible. The blocked stories from the "For You" section reappear in future results.
Tested on Windows 7 x64, Mac 10.13 and Arch Linux.

**Comment by sriniven** [comment]
I was able to reproduce this now, we will fix soon, thanks.

**Comment by sriniven** [comment]
This is fixed and tested now. Note that when you "Block a site" from the ... menu, the site will be blocked on the next refresh. Very rarely, there is a short delay for the block to kick in, like a minute or two.
Other types of feedback, like "Not Interested" etc are treated more as hints to the system and not used for hard block.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Laserlike (0.9.41) version and it is no longer reproducible. Tested on Windows 10 x64, Windows 7 x64, Mac 10.13 and Arch Linux.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using latest Laserlike (0.9.45816) version and the issue is still reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux.

**Comment by Softvision-RemusDranca** [comment]
This issue is reproducible with the latest Laserlike (0.9.45816) version. Tested on Windows 10 x64, Mac 10.13 and Arch Linux.
Considering this I will reopen the issue.

**Comment by sg-laserlike** [comment]
Here is what happens:

When an user first installs the extension, we can't personalize the For You feed because we don't have any data. So, instead of sending nothing to the user, we send the trending feed, which we don't do personalization(all feedbacks are ignored, and it makes no sense to personalize the trending feed). We will honor the feedback while generating For You feed(usually happens after user reads a few pages). 

So can you test this after the For You feed is not empty? I agree we should label the Feed(for You vs. Trending) correctly, but maybe it's not blocker?

**Comment by sriniven** [comment]
We should not be labeling anything, the feed should be considered as a
personalized feed with whatever information we have.

**Comment by Softvision-RemusDranca** [comment]
I haven't quite understood what are the next steps here. Should I proceed with testing requested by @sg-laserlike? Or there is some rework that needs to be done based on @sriniven comment?

**Comment by sg-laserlike** [comment]
@Softvision-RemusDranca We've fixed this from our backend. Please retest.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest "Advance" (0.9.45936) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux.
